Debian release 2.4.2-2

diff --git a/debian/prerm b/debian/prerm
--- a/debian/prerm
+++ b/debian/prerm
@@ -1,13 +1,40 @@
-#!/bin/sh
-# work around "fix" for potential dpkg breakage 
-#  if [ \( "$1" = "upgrade" -o "$1" = "remove" \) \
-#       -a -L /usr/doc/pdl ]; then
-#        rm -f /usr/doc/pdl
-#  fi
+#! /bin/sh
+# prerm script for pdl
+#
+# see: dh_installdeb(1)
+
+set -e
+
+# summary of how this script can be called:
+#        * <prerm> `remove'
+#        * <old-prerm> `upgrade' <new-version>
+#        * <new-prerm> `failed-upgrade' <old-version>
+#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
+#        * <deconfigured's-prerm> `deconfigure' `in-favour'
+#          <package-being-installed> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
 
 case "$1" in
-	upgrade|remove)
-		rm -rf /usr/lib/perl5/PDL/HtmlDocs
-		rm -f  /usr/lib/perl5/PDL/pdldoc.db /usr/lib/perl5/PDL/Index.pod
-		;;
+    remove|upgrade|deconfigure)
+	rm -rf /usr/share/doc/pdl/html
+	rm -f  /usr/lib/perl5/PDL/pdldoc.db /usr/lib/perl5/PDL/Index.pod
+        ;;
+    failed-upgrade)
+        ;;
+    *)
+        echo "prerm called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
 esac
+
+exit 0
+
+
